name: "🐞 Bug Report"
description: Report a bug with the Student Management System
title: "[BUG]: "
labels: ["bug"]
body:
  - type: input
    id: summary
    attributes:
      label: Bug Summary
      description: Short description of the bug
      placeholder: "e.g. Login form does not accept valid password"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide detailed steps to reproduce the issue
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: "What you expected to happen"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      placeholder: "What actually happened"
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true
